appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: true
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: "auto" 
staticResource:
  port: "7288"
  allowExt:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .bmp
log:
  level: 4
