appearance:
  defaultOpen: maximised
  width: 1024
  height: 768
window:
  GPUAccelerate: true
  webviewUserData: ""
linux:
  windowTransparent: false
  GPUStrategy: always
staticResource:
  port: "7288"
  allowExt:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
log:
  level: 4
download:
  timeout: 10
